import axios from "axios";
import { InferGetStaticPropsType } from "next";
import Head from "next/head";
import { useState } from "react";
import { useIndex } from "../../context";

export async function getStaticProps(): Promise<any> {
  try {
    // const netbetRes = await axios.get("http://localhost:3000/api/netbet");
    const ktoRes = await axios.get("http://localhost:3000/api/kto");
    const campobetRes = await axios.get("http://localhost:3000/api/campobet");
    const betanoRes = await axios.get("http://localhost:3000/api/betano");
    // const betfairRes = await axios.get("http://localhost:3000/api/betfair");

    return {
      props: {
        data: [ktoRes.data, campobetRes.data, betanoRes.data],
      },
    };
  } catch (error) {
    console.error(error);
    console.log(error);
  }
}

//Types
interface OddsTypes {
  odds: [number, number, number][];
}

export default function Home({
  data,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const { setIndex } = useIndex();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {data[2].clubs.map((club: string[], key: number) => (
          <li key={key}>
            <button onClick={() => setIndex(key)}>
              {club[0]} x {club[1]}
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}
